services:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: carstock
      MYSQL_USER: bertolo
      MYSQL_PASSWORD: bertolo123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - api-network

  car-stock-api:
    build: .
    image: car-stock-api:1.0
    ports:
      - "8080:8080"
    restart: always
    networks:
      - api-network
    depends_on:
      - mysql

networks:
  api-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local